spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange
    username: root
    password: root

  liquibase:
    change-log: classpath:/changelog/migration.xml

  data:
    web:
      pageable:
        one-indexed-parameters: true

exchange:
  currency:
    url: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
