spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange
    username: root
    password: root

  liquibase:
    change-log: classpath:/changelog/migration.xml

  data:
    web:
      pageable:
        one-indexed-parameters: true

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # by date
      max-file-size: 10MB # by size
  file:
    name: C:\Users\Hoso\IdeaProjects\Exchange\log\application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss}  %-5level %logger{36} - %msg%n"
  level:
    root: info
    com.example: info